apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: react-plotly-geo-svc
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: go-rest-api-svc
              servicePort: 8000