apiVersion: apps/v1

kind: Deployment

metadata:
  name: go-rest-api
  labels:
    app: go-rest-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
        - name: go-rest-api
          image: manguilar22/golang:rest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-svc
  labels:
    app: go-rest-api
spec:
  type: ClusterIP
  protocol: TCP
  clusterIP: none
  ports:
    - port: 8000
      targetPort: 8000
