version: "3.3"

services:

  mongodb:
    image: mongo:demo
    container_name: "restful-db"
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./model/schema
    volumes:
      - EuclideanDistance:/data/db:cached
    ports:
      - 27017:27017

  flask-restful:
    image: flask:demo
    container_name: "flask-restful-api"
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./web/
    depends_on:
      - mongodb
    ports:
      - 5000:5000

  go-rest:
    container_name: go-rest-api
    image: go:v1
    build:
      context: ./rest/
      dockerfile: Dockerfile

  react-frontend:
    image: react:demo
    container_name: "react-app"
    restart: always
    environment:
      REACT_APP_HOSTNAME: go-rest:8000
    build:
      dockerfile: Dockerfile
      context: ./client/
    depends_on:
      - go-rest
    ports:
      - 3000:3000

volumes:
  EuclideanDistance:
